### ISSUE TITLE
Core dump when create two JSIsolate

### ISSUE THREAD

**Issue by He110wor1d** [cloudflare/stpyv8#27]
I am using version 8.9.225.25，And when I run this code, I got CoreDump.

'''

    import STPyV8 as V8

    with STPyV8.JSIsolate() as iso:
        myclass = MyClass()
        print("current:",STPyV8.JSIsolate.current)
        with STPyV8.JSContext(myclass) as ctxt:
            print(ctxt.eval("this.reallyComplexFunction(2) + 10;"))

    with STPyV8.JSIsolate() as iso:
        myclass = MyClass()
        print("current:",STPyV8.JSIsolate.current)
        with STPyV8.JSContext(myclass) as ctxt:
            print(ctxt.eval("this.reallyComplexFunction(2) + 10;"))
'''

Is any wrong usage in my code?

**Comment by buffer** [comment]
Sorry for the late response but this a very busy period for me. 

I suspect this is a bug in V8 because I can reproduce the bug using version 8.9.225.25 but the problem just disappears using version 9.2.230.21. Can you please give it a try using more recent releases and let me know what you observe?

Thanks!
